apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared/ingress.yaml
  - shared/namespace.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/servicemonitor.yaml
  - backend/slo-rules.yaml
  - backend/hpa.yaml
