apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev
namespace: healthpulse-dev

resources:
  - ../../base

images:
  - name: 588738574057.dkr.ecr.us-east-1.amazonaws.com/healthpulse-backend
    newTag: a8ba6add8ca2b32f2f32317ef08f30df740b5321

patches:
  - target:
      kind: Namespace
      name: healthpulse
    patch: |-
      - op: replace
        path: /metadata/name
        value: healthpulse-dev
  - target:
      kind: HorizontalPodAutoscaler
      name: healthpulse-backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
      name: healthpulse-web-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
